#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change &> /dev/null"


yabai -m config external_bar               all:36:0       \
                window_zoom_persist        off            \
                window_origin_display      default        \
                window_placement           second_child   \
                window_topmost             on             \
                window_shadow              float          \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.6            \
                window_animation_duration  0.5            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                focus_follows_mouse        autoraise      \
                mouse_follows_focus        on             \
                                                          \
                top_padding                5              \
                bottom_padding             5              \
                left_padding               5              \
                right_padding              5              \
                window_gap                 5              \
                layout                     bsp

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|Clash Verge)$" manage=off
yabai -m rule --add app="QQ" title="图片查看器|群聊的聊天记录" manage=off
yabai -m rule --add app="pot" title="Translate|Recognize" manage=off
yabai -m rule --add app="WeChat" title="Moments|Preview|WeChat (Window)" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


borders active_color=0xfffb9322 inactive_color=0xff494d64 width=5.0

echo "yabai configuration loaded.."
