require("items.right.calendar")
require("items.right.weather")
-- require("items.right.inputsource")
require("items.right.wifi")
require("items.right.battery")
require("items.right.volume")
-- require("items.right.mail")
require("items.right.qqwechat")
require("items.right.cpu")
--require("items.right.ram")
